config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  get "top" => "home#top"
  get "about" => "home#about"
  resources :posts do
    collection do
      get :search
    end
  end
  resources :users, only: [:index, :show, :create, :edit, :update] do
    collection do
      get "signup" => "users#new"
      get "login" => "users#login_form"
      post "login" => "users#login"
      post "logout" => "users#logout"
    end
  end
  # paramsの値がparams[:post_id]に格納されるように設定
  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, :post_id, presence: true
  
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: {maximum: 140}
  validates :user_id, presence: true
  belongs_to :user

  # searchメソッドの定義
  # searchにはparams[:keryword]が入っている
  def self.search(search)
    if search
      Post.where('content LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :password, presence: true, on: :create
  validates :password, length: { in: 6..12 }, if: Proc.new { |user| user.password.present? }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  has_many :posts
  mount_uploader :image_name, ImageUploader
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  
  #これはすべてのコントローラのアクションで使える
  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  # ログインしていないユーザのアクセスを防ぐ
  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to login_users_path
    end
  end

  # すでにログインしているユーザのアクセスを防ぐ
  def forbid_login_user
    if @current_user
      flash[:notice] = "すでにログインしています"
      redirect_to root_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user

  def create
    @like = Like.new(user_id: @current_user.id, post_id: params[:post_id])
    @like.save
    redirect_to post_path(params[:post_id])
  end

  def destroy
    @like = Like.find_by(user_id: @current_user.id, post_id: params[:post_id])
    @like.destroy
    redirect_to post_path(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(5)
  end

  def show
    @likes_count = Like.where(post_id: @post.id).count
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "投稿が完了しました"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    
    if @post.update(post_params)
      flash[:notice] = "投稿を編集しました"
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to posts_path
  end

  def search
    # formで取得したパラメータにkeywordというキーをつけてモデルに送る
    @posts = Post.search(params[:keyword]).order(created_at: :desc).page(params[:page]).per(5)
  end

  private

  def post_params
    params.require(:post).permit(:content).merge(user_id: @current_user.id)
  end

  def ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @post.user_id != @current_user.id
      flash[:notice] = "権限がありません"
      redirect_to posts_path
    end
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  # ログインしていないユーザのアクセスを防ぐ
  before_action :authenticate_user, only: [:index, :show, :edit, :update]
  # すでにログインしているユーザのアクセスを防ぐ
  before_action :forbid_login_user, only: [:new, :create, :login_form, :login]
  # ログイン中のユーザと操作中のユーザが同一でないとき
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @users = User.all.order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    # 初期画像を設定
    # @user.image_name = "user_default.png"
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "登録が完了しました"
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @posts = @user.posts.page(params[:page]).per(5).order("created_at DESC")
    @likes = Like.where(user_id: @user.id).page(params[:page]).per(5).order("created_at DESC")
  end

  def edit
  end

  def update
    @user.update(user_params)

    # # 画像データが送信されたときだけ実行
    # if user_params[:image_name]
    #   # 画像のファイル名をDBに保存
    #   @user.image_name = "#{@user.id}.jpg"
    #   # 画像ファイルの情報をうけとる
    #   image = user_params[:image_name]
    #   # public/user_images配下にファイルを保存
    #   File.binwrite("public/user_images/#{@user.image_name}", image.read)
    # end
    
    if @user.save
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def login_form
    
  end

  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to root_path
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = user_params[:email]
      @password = user_params[:password]
      render :login_form
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :image_name, :password, :password_confirmation)
  end

  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="main about-main">
  <h2>TweetAppとは</h2>
  <p>
    SNSサービスです。
    近況やつぶやきを投稿し、他のユーザーと楽しくコミュニケーションできます。
  </p>
</div>

app/views/home/top.html.erb
<div class="main top-main">
  <div class="top-message">
    <h2>つぶやきで、世界はつながる</h2>
    <p>今の気持ちをつぶやいてみよう！</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kiwasaki03</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <header class="header">
      <div class="header-logo">
        <%= link_to "TweetApp", root_path %>
      </div>
      <ul class="header-menus">
        <% if @current_user %>
          <li><%= link_to @current_user.name,  user_path(@current_user.id) %></li>
          <li><%= link_to "投稿一覧", posts_path %></li>
          <li><%= link_to "投稿する", new_post_path %></li>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <li><%= link_to "ログアウト", logout_users_path, method: :post %></li>
        <% else %>
          <li><%= link_to "新規登録", signup_users_path %></li>
          <li><%= link_to "ログイン", login_users_path %></li>
        <% end %>
      </ul>
    </header>
    <% if flash[:notice] %>
      <div class="notification">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, class: "form", local: true do |f| %>
  <div class="form-body">
    <% @post.errors.full_messages.each do |message| %>
      <p class="errors"><%= message %></p>
    <% end %>
    <%= f.text_area :content, rows: 10, class: "content-area" %>
    <%= f.submit "SEND", class: "submit-btn" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="heading">編集する</h1>
    <%=  render partial: "form", locals: { post: @post } %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
    <h1 class="heading">投稿一覧</h1>
    <div class="posts">
      <% @posts.each do |post| %>
        <div class="post-item-index">
            <%= image_tag post.user.image_name.url, size: "100x100" , class: "post-item-index__image"%>
            <div class="post-item-index__text">
              <p class="post-item-index__text--username"><%= post.user.name %></p>
              <%= link_to post.content, "/posts/#{post.id}", class: "post-item-index__text--content" %>
              <div class="post-item-index__text--date">
                <p><%= l post.created_at, format: :short %></p>
              </div>
            </div>
        </div>
      <% end %>
      <%= paginate(@posts) %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="heading">投稿する</h1>
    <%=  render partial: "form", locals: { post: @post } %>
  </div>
</div>

app/views/posts/search.html.erb
<div class="main posts-index">
  <div class="container">
    <h1 class="heading">投稿一覧</h1>
    <%= form_with url: search_posts_path, local: true, method: :get, class: "search-form" do |f| %>
      <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
      <%= f.submit "検索", class: "search-btn" %>
    <% end %>
    <div class="posts">
      <% @posts.each do |post| %>
        <div class="post-item-index">
            <%= image_tag post.user.image_name.url, size: "100x100" , class: "post-item-index__image"%>
            <div class="post-item-index__text">
              <p class="post-item-index__text--username"><%= post.user.name %></p>
              <%= link_to post.content, "/posts/#{post.id}", class: "post-item-index__text--content" %>
              <div class="post-item-index__text--date">
                <p><%= l post.created_at, format: :short %></p>
              </div>
            </div>
        </div>
      <% end %>
      <%= paginate(@posts) %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="post-item">
      <div class="post-item__user">
        <%= image_tag @post.user.image_name.url, size: "100x100", class: "post-item__user--image" %>
        <%= link_to @post.user.name, user_path(@post.user.id) , class: "post-item__user--name" %>
      </div>
      <p class="post-item__content"><%= @post.content %></p>
      <div class="post-item__time">
        <%= l @post.created_at %>
      </div>
      <% if Like.find_by(user_id: @current_user.id, post_id: @post.id) %>
        <%= link_to "/likes/#{@post.id}/destroy", method: :post, class: "post-item__like-btn"  do%>
          <span class="fa fa-heart like-btn-unlike"></span>
        <% end %>
      <% else %>
        <%= link_to "/likes/#{@post.id}/create", method: :post, class: "post-item__like-btn" do %>
          <span class="fa fa-heart like-btn"></span>
        <% end %>
      <% end %>
      <span class ="post-item__count"><%= @likes_count %></p>
      <% if @current_user.id == @post.user_id%>
        <div class="post-item__menus">
          <%= link_to "編集", edit_post_path(@post.id) %>
          <%= link_to "削除", post_path(@post.id), method: :delete %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <h1 class="heading">ユーザー情報の編集</h1>
    <%= form_with model: @user, class: "users-form", local: true do |f| %>
      <div class="users-form__body">
        <% @user.errors.full_messages.each do |message| %>
        <p class="errors"><%= message %></p>
        <% end %>
        <p class="users-form__body--title">ニックネーム</p>
        <%= f.text_field :name, class: "users-form__body--field", placeholder: "nickname" %>
        <p class="users-form__body--title">メールアドレス</p>
        <%= f.text_field :email, class: "users-form__body--field", placeholder: "email" %>
        <p class="users-form__body--title">パスワード</p>
        <%= f.password_field :password, class: "users-form__body--field", placeholder: "password" %>
        <p class="users-form__body--title">パスワード（確認用）</p>
        <%= f.password_field :password_confirmation, class: "users-form__body--field", placeholder: "password" %>
        <div class="users-form__body--image">
          <%= f.label :image_name, "ファイルを選択", class:"users-form__body--image__label" %>
          <%= f.file_field :image_name, class: "users-form__body--image__file" %>
          <%= image_tag @user.image_name.url, class:"users-form__body--image__selected", id: "img_prev", size: "150x150" %>
        </div>
        <%= f.submit "保存", class:"users-form__body--btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="container">
    <h1 class="heading">ユーザー一覧</h1>
    <% @users.each do |user| %>
      <div class="users-index__item">
        <% if user.image_name %>
          <%= image_tag user.image_name.url, size: '100x80', class: "users-index__item--image" %>
        <% end %>
        <div class="users-index__item--box">
          <%= link_to user.name, user_path(user.id), class: "users-index__item--box--name" %>
        </div>
      </div>
    <% end %>
    <%= paginate(@users) %>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="main users-new">
  <div class="container">
    <h1 class="heading">ログイン</h1>
    <%= form_with model: @user, class: "users-form", local: true do |f| %>
      <% if @error_message %>
        <div class="errors">
          <%= @error_message %>
        </div>
      <% end %>
      <div class="users-form__body"> 
        <p class="users-form__body--title">メールアドレス</p>
        <%= f.text_field :email, class: "users-form__body--field", placeholder: "email", value: @email %>
        <p class="users-form__body--title">パスワード</p>
        <%= f.password_field :password, class: "users-form__body--field", placeholder: "password", value: @password %>
        <%= f.submit "login", class: "users-form__body--btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <h1 class="heading">新規ユーザー登録</h1>
    <%= form_with model: @user, class: "users-form", local: true do |f| %>
      <div class="users-form__body">
        <% @user.errors.full_messages.each do |message| %>
          <p class="errors"><%= message %></p>
        <% end %>
        <p class="users-form__body--title">ニックネーム</p>
        <%= f.text_field :name, class: "users-form__body--field", placeholder: "nickname" %>
        <p class="users-form__body--title">メールアドレス</p>
        <%= f.text_field :email, class: "users-form__body--field", placeholder: "email" %>
        <p class="users-form__body--title">パスワード</p>
        <%= f.password_field :password, class: "users-form__body--field", placeholder: "password" %>
        <p class="users-form__body--title">パスワード（再入力）</p>
        <%= f.password_field :password_confirmation, class: "users-form__body--field", placeholder: "password" %>
        <%= f.submit "signup", class: "users-form__body--btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user-info">
      <%= image_tag @user.image_name.url, size: "200x200", class: "user-info__image" %>
      <h2 class="user-info__name"><%= @user.name %></h2>
      <p class="user-info__email"><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
        <%= link_to "編集", edit_user_path(@user.id), class: "user-info__edit" %>
      <% end %>
    </div>
    <ul class="menu">
      <li><a href="#" class="menu-item active">投稿</a></li>
      <li><a href="#" class="menu-item">いいね！した投稿</a></li>
    </ul>
    <ul class="contents">
      <li class="content show">
        <% @posts.each do |post| %>
          <div class="post-item-index">
            <%= image_tag post.user.image_name.url, size: "100x100" , class: "post-item-index__image"%>
            <div class="post-item-index__text">
              <p class="post-item-index__text--username"><%= post.user.name %></p>
              <%= link_to post.content, "/posts/#{post.id}", class: "post-item-index__text--content" %>
              <div class="post-item-index__text--date">
                <p><%= l post.created_at, format: :short %></p>
              </div>
            </div>
          </div>
        <% end %>
        <%= paginate(@posts) %>
      </li>
      <li class="content">
        <% @likes.each do |like| %>
          <% liked = Post.find_by(id: like.post_id) %>
          <div class="post-item-index">
            <%= image_tag liked.user.image_name.url, size: "100x100" , class: "post-item-index__image"%>
            <div class="post-item-index__text">
              <p class="post-item-index__text--username"><%= liked.user.name %></p>
              <%= link_to liked.content, "/posts/#{liked.id}", class: "post-item-index__text--content" %>
              <div class="post-item-index__text--date">
                <p><%= l liked.created_at, format: :short %></p>
              </div>
            </div>
          </div>
        <% end %>
      </li>
    </ul>
  </div>
</div>